### ISSUE TITLE
Werbung machen

### ISSUE THREAD

**Issue by tomsrocket** [codeformuenster/alternative-skulptur-projekte#1]
- [x] WN Artikel 
- [x] Ultimo Artikel
- Claudia 
- hat Künstler aus Enschede angesprochen
- Sie könnte mal "Möhre" ansprechen
- Sie fragt mal in der Kunstakademie nach (Skulpturklassen)
- Flyer  
- Handzettel

**Comment by DirkSchemberg** [comment]
[Flyer_SchattenSkulptura_01.pdf](https://github.com/codeformuenster/alternative-skulptur-projekte/files/844045/Flyer_SchattenSkulptura_01.pdf)

Die erste Vorversion des Flyers für die Künstler, die sich beteiligen und an den Vorbereitungen mitwirken möchten.
