### ISSUE TITLE
Formular bauen

### ISSUE THREAD

**Issue by tomsrocket** [codeformuenster/alternative-skulptur-projekte#3]
Formular: Welche Daten wollen wir aufnehmen pro Event?
* Vorname / Name*
* Adresse*
* Emailadresse*
* Telefonnummer (falls das Ordnungsamt ihn erreichen muss)
* Webseite
* Muss über 18 sein
* AGBs gelesen Häkchen

Daten zur Skulptur
* Titel*
* Beschreibung* (auch z.B. wie man den Ort findet,) 
* Foto hochladen
* Bestätigung dass er die Rechte an dem Foto hat
* Kategorie*
* Ort*
* Adresse oder Koordinate*
* Öffentlicher oder privater Raum*
* Zeit der Ausstellung* (Datum) (Auch Jochen beachten, der nur 4x im August aufmachen will)
* Öffnungszeiten (Textfeld)
* Digitale Skulptur: Link
=> Live nach Freischaltung (will Thomas)
=> Beim Abschicken muss man eine Email bekommen
=> Man bekommt eine Nummer für die Skulptur in der Email
=> 5EUR pro Anmeldung 

Daten zum Ort
* Toiletten vor Ort verfügbar?
* Wickelmöglichkeit für Babies?
* Rollstuhlgerechte Zugangsmöglichkeit zu WC?
* Sonstiges zu Sanitären Anlagen?
* Wo ist alternativ die nächste WC-Gelegenheit gelegen?

Mit * gekennzeichnet = Pflicht

**Comment by todendah** [comment]
Hast du nicht eben erwähnt, dass das Formular schon fertig ist?

**Comment by tomsrocket** [comment]
Hier ist der IFRAME Code: 

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdrXhmA0onlcX2vZTlSv-Co8OyFP9xEpZsJw7UPvoml6E92-Q/viewform?embedded=true" width="760" height="500" frameborder="0" marginheight="0" marginwidth="0">Wird geladen...</iframe>

**Comment by tomsrocket** [comment]
Wäre total super, die Formularseite auf iframe umzubauen!!1! :-)

**Comment by todendah** [comment]
Sollte nun so funktionieren wie gewollt. Vielen Dank @ubergesundheit für die Hinweise!
